- alias: Harmony
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    from: 'Select a Activity'
  action:
    - service: remote.turn_on
      entity_id: remote.logitech_harmony
      data_template:
        activity: >
          {% if is_state("input_select.harmony", "Power Off") %}
             -1
          {% elif is_state("input_select.harmony", "Watch Movie") %}
            24547643
          {% elif is_state("input_select.harmony", "Play PS3") %}
            24547899
          {% elif is_state("input_select.harmony", "Play PS4") %}
            24551019
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select a Activity"

- alias: Harmony Off
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    to: 'Power Off'
  action:
    - service: remote.turn_off
      entity_id: remote.logitech_harmony
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select a Activity"
