homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 59.2783646
  longitude: 18.1058604
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 11
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_pass
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: kerry.duckdns.org:8123
  #ssl_certificate: /etc/letsencrypt/live/kerry.duckdns.org/fullchain.pem
  #ssl_key: /etc/letsencrypt/live/kerry.duckdns.org/privkey.pem
  login_attempts_threshold: 3
  #trusted_networks: 192.168.1.1

# Checks for available updates
updater:
# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:

# Track the sun
sun:

weather:
  - platform: openweathermap
    api_key: af775033b8b45587900e5c138415147f
    monitored_conditions:
      - weather
      - temperature

# Text to speech
tts:
  platform: google

vera:
  vera_controller_url: !secret veraIP
  exclude: [ 111, 112, 113 ]

light:
  platform: hue
  host: 192.168.1.9
  allow_unreachable: true

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: admin
    password: !secret asus_pass
    interval_seconds: 10
    consider_home: 180
    track_new_devices: false
    protocol: telnet

remote:
  - platform: harmony
    name: hh_basment
    host: !secret harmonyIP
    port: 5222
    username: !secret email
    password: !secret harmony_pass
    activity: Play PS4

verisure:
  username: !secret email
  password: !secret veri_pass
  thermometers: 1
  hygrometers: 1
  smartplugs: 1
  alarm: 1

notify:
  platform: pushbullet
  api_key: o.xRgpVmDFNvxtki6jIGiRUaRM5VPhv6Tr
  name: pushbullet

group: !include groups.yaml

input_select:
  playroom_hub:
    name: Playroom Hub
    options:
      - Powered Off
      - Play PS4
      - Play PS3
      - Film
    initial: Powered Off
    icon: mdi:monitor

#customize:
#  - entity_id: sensor.vardagsrum_humidity
#    icon: mdi:water-percent
