homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 11
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

frontend:

http:
  api_password: !secret http_pass
  base_url: !secret duckdns
  ssl_certificate: !secret sslcert
  ssl_key: !secret sslkey
  login_attempts_threshold: 3
  #trusted_networks: 192.168.1.1

updater:

discovery:
  ignore:
    - samsung_tv

history:

logbook:

config:

sun:

# Text to speech
tts:
  platform: google

vera:
  vera_controller_url: !secret veraIP
  exclude: [ 108, 111, 112, 113 ]

light:
  platform: hue
  host: 192.168.1.9
  allow_unreachable: true

mqtt:
  broker: !secret CLOUTMQTT_SERVER
  port: !secret CLOUDMQTT_PORT
  username: !secret CLOUDMQTT_USER
  password: !secret CLOUDMQTT_PASSWORD

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: admin
    password: !secret asus_pass
    interval_seconds: 10
    consider_home: 180
    track_new_devices: false
    protocol: telnet
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
    waypoint_whitelist:
      - kerry

remote:
  - platform: harmony
    name: logitech_harmony
    host: !secret harmonyIP
    port: 5222
    username: !secret email
    password: !secret harmony_pass
    activity: Play PS4

verisure:
  username: !secret email
  password: !secret veri_pass
  thermometers: 1
  hygrometers: 1
  smartplugs: 1
  alarm: 1

notify:
  platform: pushbullet
  api_key: !secret pushbulletAPI
  name: pushbullet

input_select:
     harmony:
       name: Harmony Control
       options:
        - Select a Activity
        - Power Off
        - Watch Movie
        - Play Wii
        - Play PS4
       icon: mdi:monitor

zone:
  name: Hemma
  latitude: !secret zone_lat
  longitude: 18.105791
  radius: 20
  icon: mdi:home

zone 2:
  name: Ooyala
  latitude: !secret zone2_lat
  longitude: 18.033360
  radius: 150
  icon: mdi:work

zone 3:
  name: Skolan
  latitude: !secret zone3_lat
  longitude: 18.113451
  radius: 150
  icon: mdi:school


sensor: !include sensors.yaml
media_player: !include mediaplayers.yaml
automation: !include automation.yaml
group: !include groups.yaml
