- platform: darksky
  api_key: !secret darkskyAPI
  monitored_conditions:
    - summary
    - cloud_cover
    - temperature
  update_inverval: '01:00'
  forecast:
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: load_5m
- platform: template
  sensors:
    current_activity:
      friendly_name: 'Current Activity'
      value_template: '{{ states.remote.logitech_harmony.attributes.current_activity }}'
